from pages.leave_page import LeavePage
from pages.admin_page import AdminPage
from pages.buzz_page import BuzzPage
from pages.claim_page import ClaimPage
from pages.dashboard_page import DashboardPage
from pages.directory_page import DirectoryPage
from pages.login_page import LoginPage
from pages.maintenance_page import MaintenancePage
from pages.my_info_page import MyInfoPage
from pages.performance_page import PerformancePage
from pages.PIM_page import PIMPage
from pages.recruitment_page import RecruitmentPage
from pages.amazon_login_page import AmazonLoginPage
from pages.amazon_my_account_page import AmazonMyAccountPage
from pages.amazon_main_page import AmazonMainPage
from pages.time_page import TimePage
